import json

# Créer la structure complète du notebook
notebook = {
    "cells": [
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "# TP: Génération Automatique de Paroles de Chanson\n",
                "\n",
                "## Objectif\n",
                "Développer un modèle de Machine Learning pour générer des paroles originales basées sur un genre musicale spécifique, en utilisant les techniques du cours (régression, classification, réseaux de neurones).\n",
                "\n",
                "## Dataset\n",
                "- **Source**: `spotify_songs.csv`\n",
                "- **Contenu**: 18,454 chansons avec paroles, genres, sous-genres et caractéristiques musicales\n",
                "\n",
                "### Approche du Projet\n",
                "1. **Analyse**: Explorer les paroles et les genres\n",
                "2. **Prétraitement**: Nettoyer et normaliser les textes\n",
                "3. **Modèle**: Construire un modèle neuronal simple pour prédire les mots suivants\n",
                "4. **Génération**: Générer des paroles conditionnées par un genre\n",
                "5. **Évaluation**: Évaluer la qualité des paroles générées"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": ["## Section 1: Chargement des Librairies et Dataset"]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "import pandas as pd\n",
                "import numpy as np\n",
                "import matplotlib.pyplot as plt\n",
                "from sklearn.model_selection import train_test_split\n",
                "from sklearn.preprocessing import LabelEncoder, OneHotEncoder\n",
                "from collections import Counter\n",
                "import re\n",
                "import string\n",
                "import warnings\n",
                "warnings.filterwarnings('ignore')\n",
                "\n",
                "# Configuration\n",
                "plt.style.use('seaborn-v0_8-darkgrid')\n",
                "%matplotlib inline\n",
                "\n",
                "print('✓ Librairies chargées avec succès!')"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Charger le dataset Spotify\n",
                "df = pd.read_csv('/home/abdou/Public/sites/cours/spotify_songs.csv')\n",
                "\n",
                "print('=== INFORMATIONS DU DATASET ===')\n",
                "print(f'Nombre d\\'exemples: {len(df):,}')\n",
                "print(f'Nombre de colonnes: {len(df.columns)}')\n",
                "print(f'\\nValeurs manquantes:')\n",
                "print(df.isnull().sum())\n",
                "print(f'\\nExemple de données:')\n",
                "print(df[['track_name', 'track_artist', 'playlist_genre', 'lyrics']].head(1).to_string())"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": ["## Section 2: Exploration et Sélection des Colonnes Utiles"]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Vérifier les genres disponibles\n",
                "print('=== GENRES MUSICAUX DISPONIBLES ===')\n",
                "genres = df['playlist_genre'].value_counts()\n",
                "print(f'Nombre de genres: {len(genres)}')\n",
                "print(f'\\nTop 15 genres:')\n",
                "print(genres.head(15))\n",
                "print(f'\\nDistribution des genres:')\n",
                "genres.head(10).plot(kind='barh', figsize=(10, 6))\n",
                "plt.xlabel('Nombre de chansons')\n",
                "plt.ylabel('Genre')\n",
                "plt.title('Distribution des 10 genres les plus représentés')\n",
                "plt.tight_layout()\n",
                "plt.show()"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Nettoyer les données: garder seulement les lignes avec des paroles valides\n",
                "print('=== NETTOYAGE DES DONNÉES ===')\n",
                "print(f'Avant nettoyage: {len(df)} lignes')\n",
                "\n",
                "# Supprimer les paroles manquantes ou courtes\n",
                "df = df[df['lyrics'].notna()].copy()\n",
                "df = df[df['lyrics'].str.len() > 50].copy()\n",
                "df = df[df['lyrics'] != 'NA'].copy()\n",
                "\n",
                "print(f'Après nettoyage: {len(df)} lignes')\n",
                "print(f'\\nTaille moyenne des paroles: {df[\"lyrics\"].str.len().mean():.0f} caractères')\n",
                "print(f'Nombre moyen de mots: {(df[\"lyrics\"].str.split().str.len().mean()):.0f} mots')\n",
                "\n",
                "# Vérifier la distribution par genre\n",
                "print(f'\\nDistribution des genres après nettoyage:')\n",
                "print(df['playlist_genre'].value_counts().head(10))"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": ["## Section 3: Nettoyage et Normalisation du Texte"]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Fonction de prétraitement du texte\n",
                "def preprocess_text(text):\n",
                "    \"\"\"\n",
                "    Nettoie et normalise le texte selon les directives du cours:\n",
                "    1. Minuscule\n",
                "    2. Suppression des caractères indésirables\n",
                "    3. Gestion de la ponctuation\n",
                "    4. Tokens spéciaux\n",
                "    \"\"\"\n",
                "    # Convertir en minuscule\n",
                "    text = text.lower()\n",
                "    \n",
                "    # Remplacer les sauts de ligne par un token spécial\n",
                "    text = text.replace('\\\\n', ' <NEW_LINE> ')\n",
                "    text = text.replace('\\n', ' <NEW_LINE> ')\n",
                "    \n",
                "    # Garder seulement les caractères alphanumériques et ponctuation de base\n",
                "    text = re.sub(r'[^a-z0-9\\s\\'\\-,.:!?()]', '', text)\n",
                "    \n",
                "    # Supprimer les espaces multiples\n",
                "    text = re.sub(r'\\s+', ' ', text).strip()\n",
                "    \n",
                "    return text\n",
                "\n",
                "# Appliquer le prétraitement\n",
                "print('Prétraitement du texte des paroles...')\n",
                "df['lyrics_clean'] = df['lyrics'].apply(preprocess_text)\n",
                "\n",
                "# Vérifier le résultat\n",
                "print('\\nExemple avant:')\n",
                "print(df['lyrics'].iloc[0][:200])\n",
                "print('\\nExemple après:')\n",
                "print(df['lyrics_clean'].iloc[0][:200])"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Tokenization\n",
                "def tokenize(text):\n",
                "    \"\"\"Convertir le texte en tokens\"\"\"\n",
                "    return text.split()\n",
                "\n",
                "print('Tokenization des paroles...')\n",
                "df['tokens'] = df['lyrics_clean'].apply(tokenize)\n",
                "\n",
                "print(f'\\nExemple de tokens: {df[\"tokens\"].iloc[0][:20]}')\n",
                "print(f'\\nNombre moyen de tokens: {df[\"tokens\"].str.len().mean():.0f}')\n",
                "print(f'Nombre max de tokens: {df[\"tokens\"].str.len().max():.0f}')"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": ["## Section 4: Création du Vocabulaire et Encodage"]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Construire le vocabulaire à partir de tous les tokens\n",
                "print('Construction du vocabulaire...')\n",
                "\n",
                "# Compter la fréquence des mots\n",
                "all_tokens = []\n",
                "for tokens_list in df['tokens']:\n",
                "    all_tokens.extend(tokens_list)\n",
                "\n",
                "word_freq = Counter(all_tokens)\n",
                "print(f'Nombre total de tokens distincts: {len(word_freq)}')\n",
                "\n",
                "# Définir un seuil de fréquence\n",
                "MIN_FREQ = 2\n",
                "vocab = {word: freq for word, freq in word_freq.items() if freq >= MIN_FREQ}\n",
                "print(f'Vocabulaire après seuil MIN_FREQ={MIN_FREQ}: {len(vocab)} mots')\n",
                "\n",
                "# Afficher les mots les plus fréquents\n",
                "print(f'\\nTop 20 mots les plus fréquents:')\n",
                "for word, freq in sorted(word_freq.items(), key=lambda x: x[1], reverse=True)[:20]:\n",
                "    print(f'{word}: {freq}')"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Créer le dictionnaire word2idx et idx2word\n",
                "# Tokens spéciaux\n",
                "SPECIAL_TOKENS = ['<PAD>', '<UNK>', '<BOS>', '<EOS>']\n",
                "\n",
                "word2idx = {token: idx for idx, token in enumerate(SPECIAL_TOKENS)}\n",
                "idx = len(SPECIAL_TOKENS)\n",
                "\n",
                "for word in sorted(vocab.keys()):\n",
                "    word2idx[word] = idx\n",
                "    idx += 1\n",
                "\n",
                "idx2word = {idx: word for word, idx in word2idx.items()}\n",
                "\n",
                "PAD_IDX = word2idx['<PAD>']\n",
                "UNK_IDX = word2idx['<UNK>']\n",
                "BOS_IDX = word2idx['<BOS>']\n",
                "EOS_IDX = word2idx['<EOS>']\n",
                "\n",
                "print(f'Vocabulaire total: {len(word2idx)} tokens')\n",
                "print(f'PAD_IDX={PAD_IDX}, UNK_IDX={UNK_IDX}, BOS_IDX={BOS_IDX}, EOS_IDX={EOS_IDX}')\n",
                "print(f'\\nExemples d\\'encodage:')\n",
                "for word in ['love', 'heart', 'night', 'music']:\n",
                "    if word in word2idx:\n",
                "        print(f'{word} -> {word2idx[word]}')"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Fonction pour encoder les tokens\n",
                "def encode_tokens(tokens, word2idx, max_len=None):\n",
                "    \"\"\"Convertir les tokens en indices\"\"\"\n",
                "    encoded = [word2idx.get(token, UNK_IDX) for token in tokens]\n",
                "    \n",
                "    if max_len:\n",
                "        if len(encoded) > max_len:\n",
                "            encoded = encoded[:max_len]  # Troncature\n",
                "        else:\n",
                "            encoded += [PAD_IDX] * (max_len - len(encoded))  # Padding\n",
                "    \n",
                "    return encoded\n",
                "\n",
                "# Analyser la longueur des tokens\n",
                "lengths = df['tokens'].str.len()\n",
                "print(f'Statistiques des longueurs:')\n",
                "print(f'Min: {lengths.min()}, Max: {lengths.max()}, Mean: {lengths.mean():.0f}, Median: {lengths.median():.0f}')\n",
                "\n",
                "# Choisir une longueur maximale (90e percentile)\n",
                "MAX_SEQ_LEN = int(np.percentile(lengths, 90))\n",
                "print(f'\\nLongueur maximale choisie: {MAX_SEQ_LEN}')\n",
                "\n",
                "# Encoder tous les tokens\n",
                "print('Encodage des tokens...')\n",
                "df['encoded_tokens'] = df['tokens'].apply(lambda x: encode_tokens(x, word2idx, MAX_SEQ_LEN))\n",
                "\n",
                "print('✓ Encodage terminé')\n",
                "print(f'Exemple d\\'encoded_tokens: {df[\"encoded_tokens\"].iloc[0][:20]}')"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": ["## Section 5: Préparation des Jeux d'Entraînement et Validation"]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Sélectionner les genres principaux pour simplifier l'apprentissage\n",
                "TOP_GENRES = 5\n",
                "top_genres = df['playlist_genre'].value_counts().head(TOP_GENRES).index.tolist()\n",
                "print(f'Genres sélectionnés pour l\\'entraînement:')\n",
                "for i, g in enumerate(top_genres, 1):\n",
                "    count = len(df[df['playlist_genre'] == g])\n",
                "    print(f'{i}. {g}: {count} chansons')\n",
                "\n",
                "# Filtrer le dataset\n",
                "df_filtered = df[df['playlist_genre'].isin(top_genres)].copy()\n",
                "print(f'\\nDataset filtré: {len(df_filtered)} chansons')"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Encoder les genres\n",
                "genre_encoder = LabelEncoder()\n",
                "df_filtered['genre_encoded'] = genre_encoder.fit_transform(df_filtered['playlist_genre'])\n",
                "\n",
                "print('Encodage des genres:')\n",
                "for i, genre in enumerate(genre_encoder.classes_):\n",
                "    print(f'Genre {i}: {genre}')\n",
                "\n",
                "NUM_GENRES = len(genre_encoder.classes_)"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Créer les paires (input, target) pour la prédiction du mot suivant\n",
                "X = []\n",
                "y = []\n",
                "genres_list = []\n",
                "\n",
                "for idx, row in df_filtered.iterrows():\n",
                "    tokens = row['encoded_tokens']\n",
                "    genre = row['genre_encoded']\n",
                "    \n",
                "    # Pour chaque position, créer une paire (contexte, target)\n",
                "    for i in range(len(tokens) - 1):\n",
                "        X.append(tokens[:i+1])\n",
                "        y.append(tokens[i+1])\n",
                "        genres_list.append(genre)\n",
                "\n",
                "print(f'Nombre d\\'exemples créés: {len(X)}')\n",
                "print(f'Exemple d\\'entrée: {X[0]}')\n",
                "print(f'Exemple de cible: {y[0]} (mot: {idx2word.get(y[0], \"UNK\")})')\n",
                "print(f'Genre: {genre_encoder.inverse_transform([genres_list[0]])[0]}')"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Convertir en arrays numpy et redimensionner X\n",
                "def pad_sequence(seq, max_len):\n",
                "    \"\"\"Assurer que toutes les séquences ont la même longueur\"\"\"\n",
                "    if len(seq) == max_len:\n",
                "        return seq\n",
                "    elif len(seq) < max_len:\n",
                "        return seq + [PAD_IDX] * (max_len - len(seq))\n",
                "    else:\n",
                "        return seq[-max_len:]\n",
                "\n",
                "SEQ_LEN = 10  # Longueur des séquences pour l'entrée\n",
                "X_padded = np.array([pad_sequence(seq, SEQ_LEN) for seq in X])\n",
                "y_array = np.array(y)\n",
                "genres_array = np.array(genres_list)\n",
                "\n",
                "print(f'Shape de X: {X_padded.shape}')\n",
                "print(f'Shape de y: {y_array.shape}')\n",
                "print(f'Shape de genres: {genres_array.shape}')"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Diviser en train/validation\n",
                "X_train, X_val, y_train, y_val, genres_train, genres_val = train_test_split(\n",
                "    X_padded, y_array, genres_array,\n",
                "    test_size=0.2,\n",
                "    random_state=42\n",
                ")\n",
                "\n",
                "print(f'Ensemble d\\'entraînement: {X_train.shape[0]} exemples')\n",
                "print(f'Ensemble de validation: {X_val.shape[0]} exemples')\n",
                "print(f'\\nDistribution des genres (train):')\n",
                "for genre_idx in range(NUM_GENRES):\n",
                "    count = (genres_train == genre_idx).sum()\n",
                "    print(f'Genre {genre_encoder.inverse_transform([genre_idx])[0]}: {count}')"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": ["## Section 6: Construction du Modèle Neural Network"]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Classe du modèle Neural Network simple (inspiré du cours)\n",
                "class LyricsGenerationModel:\n",
                "    \"\"\"\n",
                "    Modèle simple de génération de paroles.\n",
                "    Architecture:\n",
                "    - Embedding d'entrée: convertit les indices de mots en vecteurs\n",
                "    - Embedding de condition: convertit le genre en vecteur\n",
                "    - Couche cachée: applique une transformation\n",
                "    - Sortie: logits pour chaque mot du vocabulaire\n",
                "    \"\"\"\n",
                "    \n",
                "    def __init__(self, vocab_size, embedding_dim=16, hidden_dim=32, num_genres=5):\n",
                "        self.vocab_size = vocab_size\n",
                "        self.embedding_dim = embedding_dim\n",
                "        self.hidden_dim = hidden_dim\n",
                "        self.num_genres = num_genres\n",
                "        \n",
                "        # Initialiser les poids aléatoirement\n",
                "        np.random.seed(42)\n",
                "        \n",
                "        # Embedding pour les mots (vocab_size x embedding_dim)\n",
                "        self.word_embedding = np.random.randn(vocab_size, embedding_dim) * 0.01\n",
                "        \n",
                "        # Embedding pour les genres (num_genres x embedding_dim)\n",
                "        self.genre_embedding = np.random.randn(num_genres, embedding_dim) * 0.01\n",
                "        \n",
                "        # Poids de la couche cachée: (SEQ_LEN * embedding_dim + embedding_dim) -> hidden_dim\n",
                "        self.W1 = np.random.randn(SEQ_LEN * embedding_dim + embedding_dim, hidden_dim) * 0.01\n",
                "        self.b1 = np.zeros((1, hidden_dim))\n",
                "        \n",
                "        # Poids de sortie: hidden_dim -> vocab_size\n",
                "        self.W2 = np.random.randn(hidden_dim, vocab_size) * 0.01\n",
                "        self.b2 = np.zeros((1, vocab_size))\n",
                "        \n",
                "        self.loss_history = []\n",
                "        self.val_loss_history = []\n",
                "    \n",
                "    def forward(self, X_batch, genres_batch):\n",
                "        \"\"\"\n",
                "        Forward pass du modèle.\n",
                "        X_batch: (batch_size, SEQ_LEN) - indices des mots\n",
                "        genres_batch: (batch_size,) - indices des genres\n",
                "        \"\"\"\n",
                "        batch_size = X_batch.shape[0]\n",
                "        \n",
                "        # Embedding des mots\n",
                "        word_embeds = self.word_embedding[X_batch]  # (batch_size, SEQ_LEN, embedding_dim)\n",
                "        word_embeds_flat = word_embeds.reshape(batch_size, -1)  # Aplatir\n",
                "        \n",
                "        # Embedding du genre\n",
                "        genre_embeds = self.genre_embedding[genres_batch]  # (batch_size, embedding_dim)\n",
                "        \n",
                "        # Concaténer les embeddings\n",
                "        combined = np.concatenate([word_embeds_flat, genre_embeds], axis=1)  # (batch_size, SEQ_LEN*embedding_dim + embedding_dim)\n",
                "        \n",
                "        # Couche cachée avec activation ReLU\n",
                "        z1 = np.dot(combined, self.W1) + self.b1\n",
                "        a1 = np.maximum(z1, 0)  # ReLU\n",
                "        \n",
                "        # Couche de sortie (logits)\n",
                "        z2 = np.dot(a1, self.W2) + self.b2\n",
                "        \n",
                "        return z2, a1, combined\n",
                "    \n",
                "    def compute_loss(self, logits, y_batch):\n",
                "        \"\"\"\n",
                "        Calcul de la perte (cross-entropy).\n",
                "        Cross-entropy habituelle du cours: J = -(1/m) * sum(y * log(p))\n",
                "        \"\"\"\n",
                "        batch_size = logits.shape[0]\n",
                "        \n",
                "        # Softmax pour obtenir les probabilités\n",
                "        exp_logits = np.exp(logits - np.max(logits, axis=1, keepdims=True))\n",
                "        probs = exp_logits / np.sum(exp_logits, axis=1, keepdims=True)\n",
                "        \n",
                "        # Cross-entropy loss\n",
                "        correct_log_probs = -np.log(probs[np.arange(batch_size), y_batch])\n",
                "        loss = np.mean(correct_log_probs)\n",
                "        \n",
                "        return loss, probs\n",
                "    \n",
                "    def backward(self, X_batch, genres_batch, y_batch, logits, a1, combined, probs, learning_rate=0.01):\n",
                "        \"\"\"\n",
                "        Backward pass (gradient descent comme dans le cours).\n",
                "        \"\"\"\n",
                "        batch_size = X_batch.shape[0]\n",
                "        \n",
                "        # Gradient de la perte par rapport aux logits\n",
                "        d_logits = probs.copy()\n",
                "        d_logits[np.arange(batch_size), y_batch] -= 1\n",
                "        d_logits /= batch_size\n",
                "        \n",
                "        # Gradient W2 et b2\n",
                "        dW2 = np.dot(a1.T, d_logits)\n",
                "        db2 = np.sum(d_logits, axis=0, keepdims=True)\n",
                "        \n",
                "        # Gradient d_a1\n",
                "        d_a1 = np.dot(d_logits, self.W2.T)\n",
                "        \n",
                "        # Appliquer la dérivée de ReLU\n",
                "        d_z1 = d_a1 * (a1 > 0)\n",
                "        \n",
                "        # Gradient W1 et b1\n",
                "        dW1 = np.dot(combined.T, d_z1)\n",
                "        db1 = np.sum(d_z1, axis=0, keepdims=True)\n",
                "        \n",
                "        # Mise à jour des poids (descente de gradient)\n",
                "        self.W2 -= learning_rate * dW2\n",
                "        self.b2 -= learning_rate * db2\n",
                "        self.W1 -= learning_rate * dW1\n",
                "        self.b1 -= learning_rate * db1\n",
                "\n",
                "print('✓ Modèle défini avec succès!')"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": ["## Section 7: Entraînement du Modèle"]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Créer le modèle\n",
                "model = LyricsGenerationModel(\n",
                "    vocab_size=len(word2idx),\n",
                "    embedding_dim=16,\n",
                "    hidden_dim=32,\n",
                "    num_genres=NUM_GENRES\n",
                ")\n",
                "\n",
                "print(f'Modèle créé avec:')\n",
                "print(f'- Taille du vocabulaire: {len(word2idx)}')\n",
                "print(f'- Dimension d\\'embedding: 16')\n",
                "print(f'- Dimension cachée: 32')\n",
                "print(f'- Nombre de genres: {NUM_GENRES}')"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Fonction d'entraînement\n",
                "def train_epoch(model, X_train, y_train, genres_train, batch_size=128, learning_rate=0.01):\n",
                "    \"\"\"Entraîner une époque complète\"\"\"\n",
                "    total_loss = 0\n",
                "    num_batches = len(X_train) // batch_size\n",
                "    \n",
                "    for batch_idx in range(num_batches):\n",
                "        start_idx = batch_idx * batch_size\n",
                "        end_idx = min(start_idx + batch_size, len(X_train))\n",
                "        \n",
                "        X_batch = X_train[start_idx:end_idx]\n",
                "        y_batch = y_train[start_idx:end_idx]\n",
                "        genres_batch = genres_train[start_idx:end_idx]\n",
                "        \n",
                "        # Forward pass\n",
                "        logits, a1, combined = model.forward(X_batch, genres_batch)\n",
                "        loss, probs = model.compute_loss(logits, y_batch)\n",
                "        \n",
                "        # Backward pass (gradient descent)\n",
                "        model.backward(X_batch, genres_batch, y_batch, logits, a1, combined, probs, learning_rate)\n",
                "        \n",
                "        total_loss += loss\n",
                "    \n",
                "    return total_loss / num_batches\n",
                "\n",
                "def evaluate(model, X_test, y_test, genres_test, batch_size=128):\n",
                "    \"\"\"Évaluer le modèle sur un ensemble de validation\"\"\"\n",
                "    total_loss = 0\n",
                "    num_batches = len(X_test) // batch_size\n",
                "    \n",
                "    for batch_idx in range(num_batches):\n",
                "        start_idx = batch_idx * batch_size\n",
                "        end_idx = min(start_idx + batch_size, len(X_test))\n",
                "        \n",
                "        X_batch = X_test[start_idx:end_idx]\n",
                "        y_batch = y_test[start_idx:end_idx]\n",
                "        genres_batch = genres_test[start_idx:end_idx]\n",
                "        \n",
                "        logits, _, _ = model.forward(X_batch, genres_batch)\n",
                "        loss, _ = model.compute_loss(logits, y_batch)\n",
                "        total_loss += loss\n",
                "    \n",
                "    return total_loss / num_batches"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Entraîner le modèle\n",
                "NUM_EPOCHS = 15\n",
                "BATCH_SIZE = 128\n",
                "LEARNING_RATE = 0.001\n",
                "BEST_VAL_LOSS = float('inf')\n",
                "PATIENCE = 3\n",
                "patience_counter = 0\n",
                "\n",
                "print(f'Début de l\\'entraînement...')\n",
                "print(f'Époque\\tLoss Train\\tLoss Val')\n",
                "print('-' * 40)\n",
                "\n",
                "for epoch in range(NUM_EPOCHS):\n",
                "    # Entraînement\n",
                "    train_loss = train_epoch(model, X_train, y_train, genres_train, BATCH_SIZE, LEARNING_RATE)\n",
                "    \n",
                "    # Validation\n",
                "    val_loss = evaluate(model, X_val, y_val, genres_val, BATCH_SIZE)\n",
                "    \n",
                "    model.loss_history.append(train_loss)\n",
                "    model.val_loss_history.append(val_loss)\n",
                "    \n",
                "    print(f'{epoch+1}\\t{train_loss:.4f}\\t\\t{val_loss:.4f}')\n",
                "    \n",
                "    # Early stopping\n",
                "    if val_loss < BEST_VAL_LOSS:\n",
                "        BEST_VAL_LOSS = val_loss\n",
                "        patience_counter = 0\n",
                "    else:\n",
                "        patience_counter += 1\n",
                "        if patience_counter >= PATIENCE:\n",
                "            print(f'\\nEarly stopping à l\\'époque {epoch+1}')\n",
                "            break\n",
                "\n",
                "print('\\n✓ Entraînement terminé!')"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Visualiser l'historique de la perte\n",
                "plt.figure(figsize=(10, 6))\n",
                "plt.plot(range(1, len(model.loss_history) + 1), model.loss_history, label='Train Loss', marker='o')\n",
                "plt.plot(range(1, len(model.val_loss_history) + 1), model.val_loss_history, label='Validation Loss', marker='s')\n",
                "plt.xlabel('Époque')\n",
                "plt.ylabel('Perte (Cross-Entropy)')\n",
                "plt.title('Évolution de la Perte pendant l\\'Entraînement')\n",
                "plt.legend()\n",
                "plt.grid(True, alpha=0.3)\n",
                "plt.tight_layout()\n",
                "plt.show()"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": ["## Section 8: Génération de Paroles"]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "def generate_lyrics(model, genre_idx, max_length=50, temperature=1.0, seed_tokens=None):\n",
                "    \"\"\"\n",
                "    Générer des paroles de manière auto-régressive.\n",
                "    \n",
                "    Approche:\n",
                "    1. Commencer avec un token BOS\n",
                "    2. Prédire le mot suivant basé sur le contexte et le genre\n",
                "    3. Ajouter ce mot au contexte et répéter\n",
                "    \n",
                "    Temperature: contrôle la diversité\n",
                "        - temperature < 1: prédictions plus déterministes\n",
                "        - temperature > 1: prédictions plus aléatoires\n",
                "    \"\"\"\n",
                "    \n",
                "    if seed_tokens is None:\n",
                "        # Commencer avec BOS\n",
                "        generated_tokens = [BOS_IDX]\n",
                "    else:\n",
                "        generated_tokens = seed_tokens.copy()\n",
                "    \n",
                "    # Buffer de contexte (garder les derniers tokens)\n",
                "    context_buffer = generated_tokens[-SEQ_LEN:] if len(generated_tokens) >= 1 else generated_tokens\n",
                "    \n",
                "    for _ in range(max_length):\n",
                "        # Préparer l'entrée\n",
                "        X_input = np.array([pad_sequence(context_buffer, SEQ_LEN)])\n",
                "        genres_input = np.array([genre_idx])\n",
                "        \n",
                "        # Forward pass\n",
                "        logits, _, _ = model.forward(X_input, genres_input)\n",
                "        logits = logits[0]  # (vocab_size,)\n",
                "        \n",
                "        # Appliquer la température\n",
                "        logits = logits / temperature\n",
                "        \n",
                "        # Softmax\n",
                "        exp_logits = np.exp(logits - np.max(logits))\n",
                "        probs = exp_logits / np.sum(exp_logits)\n",
                "        \n",
                "        # Sélectionner le prochain token (sampling aléatoire pondéré)\n",
                "        next_token = np.random.choice(len(probs), p=probs)\n",
                "        \n",
                "        # Condition d'arrêt\n",
                "        if next_token == EOS_IDX:\n",
                "            break\n",
                "        \n",
                "        generated_tokens.append(next_token)\n",
                "        context_buffer.append(next_token)\n",
                "        if len(context_buffer) > SEQ_LEN:\n",
                "            context_buffer = context_buffer[-SEQ_LEN:]\n",
                "    \n",
                "    return generated_tokens\n",
                "\n",
                "print('✓ Fonction de génération prête!')"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "def tokens_to_lyrics(token_indices, idx2word):\n",
                "    \"\"\"\n",
                "    Convertir les indices de tokens en texte lisible.\n",
                "    \"\"\"\n",
                "    words = []\n",
                "    for token_idx in token_indices:\n",
                "        if token_idx == '\n",
                "            break  # EOS\n",
                "        word = idx2word.get(token_idx, '<UNK>')\n",
                "        if word not in ['<PAD>', '<BOS>', '<EOS>']:\n",
                "            words.append(word)\n",
                "    \n",
                "    # Rejoindre les mots et ajouter les retours à la ligne là où nécessaire\n",
                "    lyrics = ' '.join(words)\n",
                "    lyrics = lyrics.replace(' <new_line> ', '\\n')\n",
                "    \n",
                "    return lyrics\n",
                "\n",
                "print('✓ Fonction de conversion prête!')"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Générer des paroles pour chaque genre\n",
                "print('=== GÉNÉRATION DE PAROLES PAR GENRE ===')\n",
                "print()\n",
                "\n",
                "for genre_idx, genre_name in enumerate(genre_encoder.classes_):\n",
                "    print(f'\\n{'='*60}')\n",
                "    print(f'Genre: {genre_name.upper()}')\n",
                "    print(f'{'='*60}')\n",
                "    \n",
                "    # Générer 2 exemples avec des températures différentes\n",
                "    for temp_idx, temperature in enumerate([0.7, 1.0], 1):\n",
                "        tokens = generate_lyrics(model, genre_idx, max_length=40, temperature=temperature)\n",
                "        lyrics = tokens_to_lyrics(tokens, idx2word)\n",
                "        \n",
                "        print(f'\\nExemple {temp_idx} (Température: {temperature}):')\n",
                "        print(f'---')\n",
                "        print(lyrics if lyrics else '(Paroles vides)')                    \n",
                "        print()"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": ["## Section 9: Post-traitement et Filtrage"]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "def filter_lyrics(lyrics, min_length=20):\n",
                "    \"\"\"\n",
                "    Post-traitement des paroles générées:\n",
                "    - Supprimer les tokens spéciaux\n",
                "    - Limiter les répétitions\n",
                "    - Vérifier la longueur minimale\n",
                "    \"\"\"\n",
                "    words = lyrics.split()\n",
                "    \n",
                "    # Filtrer les mots étranges\n",
                "    filtered_words = []\n",
                "    prev_word = None\n",
                "    repeat_count = 0\n",
                "    \n",
                "    for word in words:\n",
                "        # Limiter les répétitions (max 2 fois consécutives)\n",
                "        if word == prev_word:\n",
                "            repeat_count += 1\n",
                "            if repeat_count > 1:\n",
                "                continue\n",
                "        else:\n",
                "            repeat_count = 0\n",
                "            prev_word = word\n",
                "        \n",
                "        filtered_words.append(word)\n",
                "    \n",
                "    # Vérifier la longueur\n",
                "    if len(filtered_words) < min_length:\n",
                "        return None\n",
                "    \n",
                "    return ' '.join(filtered_words)\n",
                "\n",
                "print('✓ Fonction de filtrage définie!')"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Générer et filtrer les paroles\n",
                "print('=== PAROLES GÉNÉRÉES ET FILTRÉES ===')\n",
                "print()\n",
                "\n",
                "generated_lyrics_db = {}\n",
                "\n",
                "for genre_idx, genre_name in enumerate(genre_encoder.classes_):\n",
                "    generated_lyrics_db[genre_name] = []\n",
                "    \n",
                "    print(f'\\n{genre_name.upper()}')\n",
                "    print('-' * 40)\n",
                "    \n",
                "    # Générer 3 paroles par genre\n",
                "    for attempt in range(5):  # Essayer 5 fois\n",
                "        tokens = generate_lyrics(model, genre_idx, max_length=50, temperature=0.8)\n",
                "        lyrics = tokens_to_lyrics(tokens, idx2word)\n",
                "        filtered = filter_lyrics(lyrics, min_length=30)\n",
                "        \n",
                "        if filtered and len(generated_lyrics_db[genre_name]) < 2:\n",
                "            generated_lyrics_db[genre_name].append(filtered)\n",
                "            print(f'\\n✓ Paroles {len(generated_lyrics_db[genre_name])}')\n",
                "            print(filtered[:200] + '...' if len(filtered) > 200 else filtered)\n",
                "\n",
                "print('\\n' + '='*40)\n",
                "print('Génération terminée!')"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": ["## Section 10: Sauvegarde et Fonction d'Inférence"]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "import pickle\n",
                "\n",
                "# Créer un dictionnaire avec tous les éléments nécessaires pour l'inférence\n",
                "inference_package = {\n",
                "    'model_weights': {\n",
                "        'word_embedding': model.word_embedding,\n",
                "        'genre_embedding': model.genre_embedding,\n",
                "        'W1': model.W1,\n",
                "        'b1': model.b1,\n",
                "        'W2': model.W2,\n",
                "        'b2': model.b2,\n",
                "    },\n",
                "    'vocab': {\n",
                "        'word2idx': word2idx,\n",
                "        'idx2word': idx2word,\n",
                "        'vocab_size': len(word2idx),\n",
                "    },\n",
                "    'config': {\n",
                "        'embedding_dim': 16,\n",
                "        'hidden_dim': 32,\n",
                "        'seq_len': SEQ_LEN,\n",
                "        'num_genres': NUM_GENRES,\n",
                "        'genres': list(genre_encoder.classes_),\n",
                "    },\n",
                "    'constants': {\n",
                "        'PAD_IDX': PAD_IDX,\n",
                "        'UNK_IDX': UNK_IDX,\n",
                "        'BOS_IDX': BOS_IDX,\n",
                "        'EOS_IDX': EOS_IDX,\n",
                "    }\n",
                "}\n",
                "\n",
                "# Sauvegarder\n",
                "with open('/home/abdou/Public/sites/cours/lyrics_model.pkl', 'wb') as f:\n",
                "    pickle.dump(inference_package, f)\n",
                "\n",
                "print('✓ Modèle sauvegardé dans: /home/abdou/Public/sites/cours/lyrics_model.pkl')\n",
                "print(f'\\nTaille du fichier: {os.path.getsize(\"/home/abdou/Public/sites/cours/lyrics_model.pkl\") / 1024:.1f} KB')"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "import os\n",
                "\n",
                "# Créer une classe d'inférence réutilisable\n",
                "class LyricsGenerator:\n",
                "    \"\"\"\n",
                "    Interface simple pour générer des paroles.\n",
                "    Charge le modèle sauvegardé et permet de générer rapidement.\n",
                "    \"\"\"\n",
                "    \n",
                "    def __init__(self, model_path):\n",
                "        with open(model_path, 'rb') as f:\n",
                "            package = pickle.load(f)\n",
                "        \n",
                "        self.word2idx = package['vocab']['word2idx']\n",
                "        self.idx2word = package['vocab']['idx2word']\n",
                "        self.PAD_IDX = package['constants']['PAD_IDX']\n",
                "        self.UNK_IDX = package['constants']['UNK_IDX']\n",
                "        self.BOS_IDX = package['constants']['BOS_IDX']\n",
                "        self.EOS_IDX = package['constants']['EOS_IDX']\n",
                "        self.SEQ_LEN = package['config']['seq_len']\n",
                "        self.genres = {i: g for i, g in enumerate(package['config']['genres'])}\n",
                "        self.model = self._load_model(package)\n",
                "    \n",
                "    def _load_model(self, package):\n",
                "        weights = package['model_weights']\n",
                "        cfg = package['config']\n",
                "        model = LyricsGenerationModel(\n",
                "            vocab_size=cfg['vocab_size'],\n",
                "            embedding_dim=cfg['embedding_dim'],\n",
                "            hidden_dim=cfg['hidden_dim'],\n",
                "            num_genres=cfg['num_genres']\n",
                "        )\n",
                "        model.word_embedding = weights['word_embedding']\n",
                "        model.genre_embedding = weights['genre_embedding']\n",
                "        model.W1 = weights['W1']\n",
                "        model.b1 = weights['b1']\n",
                "        model.W2 = weights['W2']\n",
                "        model.b2 = weights['b2']\n",
                "        return model\n",
                "    \n",
                "    def generate(self, genre, max_length=50, temperature=1.0):\n",
                "        \"\"\"Générer des paroles pour un genre donné\"\"\"\n",
                "        # Trouver l'index du genre\n",
                "        genre_idx = None\n",
                "        for idx, g in self.genres.items():\n",
                "            if g.lower() == genre.lower():\n",
                "                genre_idx = idx\n",
                "                break\n",
                "        \n",
                "        if genre_idx is None:\n",
                "            return f'Genre <{genre}> non trouvé. Genres disponibles: {list(self.genres.values())}'\n",
                "        \n",
                "        # Générer\n",
                "        tokens = generate_lyrics(self.model, genre_idx, max_length, temperature)\n",
                "        lyrics = tokens_to_lyrics(tokens, self.idx2word)\n",
                "        \n",
                "        return lyrics\n",
                "    \n",
                "    def list_genres(self):\n",
                "        return list(self.genres.values())\n",
                "\n",
                "print('✓ Classe LyricsGenerator définie!')"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Démonstration: charger et utiliser le générateur\n",
                "print('=== DÉMONSTRATION DU GÉNÉRATEUR SAUVEGARDÉ ===')\n",
                "print()\n",
                "\n",
                "generator = LyricsGenerator('/home/abdou/Public/sites/cours/lyrics_model.pkl')\n",
                "\n",
                "print(f'Genres disponibles: {generator.list_genres()}')\n",
                "print()\n",
                "\n",
                "# Générer pour un genre\n",
                "test_genre = generator.list_genres()[0]\n",
                "print(f'Génération de paroles pour le genre: {test_genre}')\n",
                "print('-' * 40)\n",
                "\n",
                "lyrics = generator.generate(test_genre, max_length=40, temperature=0.9)\n",
                "print(lyrics)\n",
                "print()\n",
                "print('✓ Le modèle est prêt pour une utilisation future!')"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Résumé et conclusions\n",
                "print('='*60)\n",
                "print('RÉSUMÉ DU TP - GÉNÉRATION DE PAROLES DE CHANSON')\n",
                "print('='*60)\n",
                "print()\n",
                "print('✓ ÉTAPES COMPLÉTÉES:')\n",
                "print('1. Chargement et exploration du dataset Spotify (18,454 chansons)')\n",
                "print('2. Nettoyage et normalisation du texte (minuscule, ponctuation, tokens)')\n",
                "print('3. Construction du vocabulaire avec encodage (word2idx, idx2word)')\n",
                "print('4. Préparation des données train/validation')\n",
                "print('5. Création d\\'un modèle neural network simple')\n",
                "print('6. Entraînement avec gradient descent et cross-entropy loss')\n",
                "print('7. Génération auto-régressive de paroles')\n",
                "print('8. Post-traitement et filtrage des paroles')\n",
                "print('9. Sauvegarde du modèle pour inférence')\n",
                "print('10. Création d\\'une classe réutilisable')\n",
                "print()\n",
                "print('📊 RÉSULTATS:')\n",
                "print(f'- Vocabulaire: {len(word2idx)} tokens')\n",
                "print(f'- Genres: {NUM_GENRES} ({\" \".join(genre_encoder.classes_)})')\n",
                "print(f'- Exemples d\\'entraînement: {len(X_train):,}')\n",
                "print(f'- Perte d\\'entraînement finale: {model.loss_history[-1]:.4f}')\n",
                "print(f'- Perte de validation finale: {model.val_loss_history[-1]:.4f}')\n",
                "print()\n",
                "print('🎵 CONCEPTS DU COURS APPLIQUÉS:')\n",
                "print('- Régression: Prédiction du mot suivant (sortie continue mappée à indices)')\n",
                "print('- Classification: Intégration du genre comme condition')\n",
                "print('- Réseaux de neurones: Architecture avec embeddings + couche cachée')\n",
                "print('- Fonction coût: Cross-entropy du cours')\n",
                "print('- Gradient descent: Mise à jour itérative des poids')\n",
                "print('- Matrices: Représentation NumPy des données et poids')\n",
                "print()\n",
                "print('💾 FICHIERS GÉNÉRÉS:')\n",
                "print('- /home/abdou/Public/sites/cours/lyrics_model.pkl')\n",
                "print()\n",
                "print('🚀 UTILISATION FUTURE:')\n",
                "print('generator = LyricsGenerator(\"/home/abdou/Public/sites/cours/lyrics_model.pkl\")')\n",
                "print('lyrics = generator.generate(\"rock\", max_length=50, temperature=0.8)')\n",
                "print()\n",
                "print('='*60)"
            ]
        }
    ],
    "metadata": {
        "kernelspec": {
            "display_name": "Python 3",
            "language": "python",
            "name": "python3"
        },
        "language_info": {
            "codemirror_mode": {
                "name": "ipython",
                "version": 3
            },
            "file_extension": ".py",
            "mimetype": "text/x-python",
            "name": "python",
            "nbconvert_exporter": "python",
            "pygments_lexer": "ipython3",
            "version": "3.9.0"
        }
    },
    "nbformat": 4,
    "nbformat_minor": 4
}
